-- Apply once with the destination schema first in search_path. This same DDL
-- serves product's historical records and the isolated live diagnostics schema.
-- There are deliberately no dependencies on the product namespace or ledger.

CREATE TABLE execution_provenance (
    provenance_id text PRIMARY KEY CHECK (provenance_id ~ '^[0-9a-f]{64}$'),
    worker_build_revision text NOT NULL CHECK (length(worker_build_revision) BETWEEN 1 AND 128),
    worker_image_digest text NOT NULL CHECK (length(worker_image_digest) BETWEEN 1 AND 128),
    model_digest text NOT NULL CHECK (length(model_digest) BETWEEN 1 AND 128),
    calibration_digest text NOT NULL CHECK (length(calibration_digest) BETWEEN 1 AND 128),
    preprocessing_identity text NOT NULL CHECK (length(preprocessing_identity) BETWEEN 1 AND 128),
    config_digest text NOT NULL CHECK (length(config_digest) BETWEEN 1 AND 128),
    policy_identity text NOT NULL CHECK (length(policy_identity) BETWEEN 1 AND 128),
    backend_build_revision text NOT NULL CHECK (length(backend_build_revision) BETWEEN 1 AND 128),
    first_seen_ns bigint NOT NULL CHECK (first_seen_ns >= 0)
);

CREATE TABLE execution_segments (
    segment_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    camera_id text NOT NULL CHECK (length(camera_id) BETWEEN 1 AND 128),
    worker_boot_id text NOT NULL CHECK (length(worker_boot_id) BETWEEN 1 AND 128),
    source_generation bigint NOT NULL CHECK (source_generation >= 0),
    stream_epoch bigint NOT NULL CHECK (stream_epoch >= 0),
    segment_ordinal bigint NOT NULL CHECK (segment_ordinal >= 0),
    storage_state text NOT NULL CHECK (storage_state IN ('OPEN', 'SEALED_PENDING', 'SEALED_FINAL', 'PRUNED_SUMMARY')),
    opened_at_ns bigint NOT NULL CHECK (opened_at_ns >= 0),
    sealed_at_ns bigint CHECK (sealed_at_ns >= opened_at_ns),
    record_count bigint NOT NULL DEFAULT 0 CHECK (record_count >= 0),
    payload_bytes bigint NOT NULL DEFAULT 0 CHECK (payload_bytes >= 0),
    UNIQUE (camera_id, worker_boot_id, source_generation, stream_epoch, segment_ordinal)
);

CREATE TABLE execution_units (
    causal_unit_id text PRIMARY KEY CHECK (length(causal_unit_id) BETWEEN 1 AND 128),
    camera_id text NOT NULL CHECK (length(camera_id) BETWEEN 1 AND 128),
    worker_boot_id text NOT NULL CHECK (length(worker_boot_id) BETWEEN 1 AND 128),
    source_generation bigint NOT NULL CHECK (source_generation >= 0),
    stream_epoch bigint NOT NULL CHECK (stream_epoch >= 0),
    causal_state text NOT NULL CHECK (causal_state IN ('COMPLETE', 'INCOMPLETE_KNOWN', 'INCOMPLETE_UNKNOWN')),
    terminal bigint NOT NULL DEFAULT 0 CHECK (terminal IN (0, 1)),
    first_observed_ns bigint NOT NULL CHECK (first_observed_ns >= 0),
    last_observed_ns bigint NOT NULL CHECK (last_observed_ns >= first_observed_ns),
    record_count bigint NOT NULL DEFAULT 0 CHECK (record_count >= 0),
    payload_bytes bigint NOT NULL DEFAULT 0 CHECK (payload_bytes >= 0)
);

CREATE TABLE execution_records (
    record_id text PRIMARY KEY CHECK (record_id ~ '^[0-9a-f]{64}$'),
    record_kind text NOT NULL CHECK (record_kind IN (
        'sdk.frame', 'policy.consume', 'model.score', 'policy.decision', 'event.delivery', 'backend.acceptance'
    )),
    camera_id text NOT NULL CHECK (length(camera_id) BETWEEN 1 AND 128),
    worker_boot_id text NOT NULL CHECK (length(worker_boot_id) BETWEEN 1 AND 128),
    source_generation bigint NOT NULL CHECK (source_generation >= 0),
    stream_epoch bigint NOT NULL CHECK (stream_epoch >= 0),
    producer text NOT NULL CHECK (length(producer) BETWEEN 1 AND 128),
    producer_sequence bigint NOT NULL CHECK (producer_sequence >= 0),
    frame_seq bigint CHECK (frame_seq >= 0),
    source_pts_ns bigint,
    observed_at_ns bigint NOT NULL CHECK (observed_at_ns >= 0),
    time_quality text NOT NULL CHECK (length(time_quality) BETWEEN 1 AND 128),
    causal_unit_id text NOT NULL REFERENCES execution_units(causal_unit_id) ON DELETE CASCADE,
    parent_record_id text CHECK (parent_record_id ~ '^[0-9a-f]{64}$'),
    segment_id bigint NOT NULL REFERENCES execution_segments(segment_id),
    provenance_id text NOT NULL REFERENCES execution_provenance(provenance_id),
    outcome text NOT NULL CHECK (length(outcome) BETWEEN 1 AND 128),
    reason text CHECK (length(reason) BETWEEN 1 AND 128),
    payload text NOT NULL CHECK (payload IS JSON),
    payload_bytes bigint NOT NULL CHECK (payload_bytes = octet_length(payload)),
    committed_at_ns bigint NOT NULL CHECK (committed_at_ns >= 0)
);
CREATE INDEX execution_records_camera_time ON execution_records(camera_id, observed_at_ns, producer_sequence);
CREATE INDEX execution_records_unit ON execution_records(causal_unit_id);
CREATE INDEX execution_records_segment ON execution_records(segment_id);
CREATE INDEX execution_records_producer_sequence
    ON execution_records(camera_id, worker_boot_id, stream_epoch, producer, producer_sequence);
CREATE INDEX execution_units_prune_order ON execution_units(terminal, last_observed_ns);

CREATE TABLE execution_coverage (
    coverage_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    camera_id text NOT NULL CHECK (length(camera_id) BETWEEN 1 AND 128),
    worker_boot_id text NOT NULL CHECK (length(worker_boot_id) BETWEEN 1 AND 128),
    source_generation bigint NOT NULL CHECK (source_generation >= 0),
    stream_epoch bigint NOT NULL CHECK (stream_epoch >= 0),
    coverage_kind text NOT NULL CHECK (coverage_kind IN (
        'MISSING_NOT_RECORDED', 'DELETED_BY_CAPACITY', 'UNKNOWN_COARSENED', 'UNKNOWN',
        'ACK_OBSERVED_PARENT_DELETED', 'ACK_OBSERVED_PARENT_UNKNOWN_COARSENED',
        'REJECTED_OVERSIZE', 'STORAGE_UNAVAILABLE'
    )),
    producer text CHECK (length(producer) BETWEEN 1 AND 128),
    from_sequence bigint CHECK (from_sequence >= 0),
    to_sequence bigint CHECK (to_sequence IS NULL OR (from_sequence IS NOT NULL AND to_sequence >= from_sequence)),
    from_ns bigint NOT NULL CHECK (from_ns >= 0),
    to_ns bigint NOT NULL CHECK (to_ns >= from_ns),
    record_count bigint NOT NULL CHECK (record_count >= 0),
    exact bigint NOT NULL CHECK (exact IN (0, 1)),
    cause text NOT NULL CHECK (length(cause) BETWEEN 1 AND 128),
    recorded_at_ns bigint NOT NULL CHECK (recorded_at_ns >= 0)
);
CREATE INDEX execution_coverage_camera_time ON execution_coverage(camera_id, from_ns, to_ns);

CREATE TABLE execution_batches (
    batch_id text PRIMARY KEY CHECK (batch_id ~ '^[0-9a-f]{64}$'),
    camera_id text NOT NULL CHECK (length(camera_id) BETWEEN 1 AND 128),
    worker_boot_id text NOT NULL CHECK (length(worker_boot_id) BETWEEN 1 AND 128),
    received_at_ns bigint NOT NULL CHECK (received_at_ns >= 0),
    accepted_records bigint NOT NULL CHECK (accepted_records >= 0),
    duplicate_records bigint NOT NULL CHECK (duplicate_records >= 0),
    rejected_records bigint NOT NULL CHECK (rejected_records >= 0),
    receipt text NOT NULL CHECK (receipt IS JSON)
);
